// skyrise-furniture/src/app/components/header/header.component.ts
import { Component, HostListener, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent implements OnInit {
  isMobileMenuOpen = false;
  isScrolled = false;

  ngOnInit(): void {
    // Check initial scroll position
    this.checkScroll();
  }

  /**
   * Toggle mobile menu open/closed state
   */
  toggleMobileMenu(): void {
    this.isMobileMenuOpen = !this.isMobileMenuOpen;
    
    // Update aria-expanded attribute
    const toggleButton = document.querySelector('.header__menu-toggle');
    if (toggleButton) {
      toggleButton.setAttribute('aria-expanded', this.isMobileMenuOpen.toString());
    }
    
    // Prevent body scroll when menu is open
    if (this.isMobileMenuOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
  }

  /**
   * Close mobile menu
   */
  closeMobileMenu(): void {
    this.isMobileMenuOpen = false;
    document.body.style.overflow = '';
  }

  /**
   * Listen for scroll events to add shadow on scroll
   */
  @HostListener('window:scroll', [])
  onWindowScroll(): void {
    this.checkScroll();
  }

  /**
   * Check scroll position
   */
  private checkScroll(): void {
    this.isScrolled = window.scrollY > 0;
  }

  /**
   * Listen for window resize to close mobile menu on desktop
   */
  @HostListener('window:resize', [])
  onWindowResize(): void {
    if (window.innerWidth >= 768 && this.isMobileMenuOpen) {
      this.closeMobileMenu();
    }
  }
}
<header class="header" [class.header--scrolled]="isScrolled">
  <div class="container">
    <div class="header__wrapper">
      <!-- Logo -->
      <a href="/" class="header__logo" aria-label="Skyrise Furniture Home">
        <span class="header__logo-text">skyrise</span>
        <span class="header__logo-accent">decor</span>
      </a>

      <!-- Navigation -->
      <nav class="header__nav" aria-label="Main navigation">
        <ul class="header__nav-list">
          <li class="header__nav-item">
            <a href="#" class="header__nav-link header__nav-link--active">Modern Furniture</a>
          </li>
        </ul>
      </nav>

      <!-- Actions -->
      <div class="header__actions">
        <button class="btn btn--secondary header__action-btn" aria-label="View less tables">
          Lets Talk!
        </button>
        
        <!-- Mobile menu toggle -->
        <button 
          class="header__menu-toggle" 
          aria-label="Toggle navigation menu"
          aria-expanded="false"
          (click)="toggleMobileMenu()">
          <span class="header__menu-toggle-line"></span>
          <span class="header__menu-toggle-line"></span>
          <span class="header__menu-toggle-line"></span>
        </button>
      </div>
    </div>
  </div>

  <!-- Mobile Navigation -->
  <nav class="header__mobile-nav" [class.header__mobile-nav--open]="isMobileMenuOpen" aria-label="Mobile navigation">
    <ul class="header__mobile-nav-list">
      <li class="header__mobile-nav-item">
        <a href="#" class="header__mobile-nav-link header__mobile-nav-link--active">Modern Furniture</a>
      </li>
    </ul>
    <button class="btn btn--secondary header__mobile-action-btn">
      Lets Talk!
    </button>
  </nav>
</header>

// skyrise-furniture-nextjs/src/components/Header/Header.tsx
'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import styles from './Header.module.css';

const Header: React.FC = () => {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [isScrolled, setIsScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 0);
    };

    const handleResize = () => {
      if (window.innerWidth >= 768 && isMobileMenuOpen) {
        setIsMobileMenuOpen(false);
      }
    };

    // Check initial scroll position
    handleScroll();

    // Add event listeners
    window.addEventListener('scroll', handleScroll);
    window.addEventListener('resize', handleResize);

    // Cleanup
    return () => {
      window.removeEventListener('scroll', handleScroll);
      window.removeEventListener('resize', handleResize);
    };
  }, [isMobileMenuOpen]);

  useEffect(() => {
    // Update body overflow when mobile menu is toggled
    if (isMobileMenuOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }

    return () => {
      document.body.style.overflow = '';
    };
  }, [isMobileMenuOpen]);

  const toggleMobileMenu = () => {
    setIsMobileMenuOpen(!isMobileMenuOpen);
  };

  return (
    <header className={`${styles.header} ${isScrolled ? styles['header--scrolled'] : ''}`}>
      <div className="container">
        <div className={styles.header__wrapper}>
          {/* Logo */}
          <Link href="http://localhost:4200" className={styles.header__logo} aria-label="Skyrise Furniture Home">
            <span className={styles.header__logoText}>skyrise</span>
            <span className={styles.header__logoAccent}>decor</span>
          </Link>

          {/* Navigation */}
          <nav className={styles.header__nav} aria-label="Main navigation">
            <ul className={styles.header__navList}>
              <li className={styles.header__navItem}>
                <a href="#" className={`${styles.header__navLink} ${styles['header__navLink--active']}`}>
                  Modern Furniture
                </a>
              </li>
            </ul>
          </nav>

          {/* Actions */}
          <div className={styles.header__actions}>
            <button className={`btn btn--secondary ${styles.header__actionBtn}`} aria-label="View less tables">
              Let&apos;s Talk!
            </button>
            
            {/* Mobile menu toggle */}
            <button 
              className={styles.header__menuToggle}
              aria-label="Toggle navigation menu"
              aria-expanded={isMobileMenuOpen}
              onClick={toggleMobileMenu}
            >
              <span className={styles.header__menuToggleLine}></span>
              <span className={styles.header__menuToggleLine}></span>
              <span className={styles.header__menuToggleLine}></span>
            </button>
          </div>
        </div>
      </div>

      {/* Mobile Navigation */}
      <nav 
        className={`${styles.header__mobileNav} ${isMobileMenuOpen ? styles['header__mobileNav--open'] : ''}`} 
        aria-label="Mobile navigation"
      >
        <ul className={styles.header__mobileNavList}>
          <li className={styles.header__mobileNavItem}>
            <a href="#" className={`${styles.header__mobileNavLink} ${styles['header__mobileNavLink--active']}`}>
              Modern Furniture
            </a>
          </li>
        </ul>
        <button className={`btn btn--secondary ${styles.header__mobileActionBtn}`}>
          Let&apos;s Talk!
        </button>
      </nav>
    </header>
  );
};

export default Header;
